[package]
name = "systemd-unit"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1.21.3"
ordered-multimap = "0.7.3"
log = "0.4.27"

[profile.release]
lto = "fat"  # reduces binary size from 4.2M to 2.1M
